apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-core
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: platform-core.country.example.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-core
                port:
                  number: 80
  tls:
    - hosts:
        - platform-core.country.example.edu
      secretName: platform-core-tls

