apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-core
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_COUNTRY_EKS_ROLE_ARN
    deployment.darkfactory.io/secret-store: aws-secrets-manager-or-external-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: platform-core
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

