apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-core
  annotations:
    deployment.darkfactory.io/secret-store: sealed-secrets-or-external-secrets
    deployment.darkfactory.io/registry-auth: country-managed-image-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: platform-core
  annotations:
    metallb.universe.tf/address-pool: country-public

