apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-core
  annotations:
    iam.gke.io/gcp-service-account: platform-core@PROJECT_ID.iam.gserviceaccount.com
    deployment.darkfactory.io/secret-store: google-secret-manager-or-external-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: platform-core
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

