apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-core
  annotations:
    azure.workload.identity/client-id: REPLACE_WITH_COUNTRY_MANAGED_IDENTITY_CLIENT_ID
    deployment.darkfactory.io/secret-store: azure-key-vault-or-external-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: platform-core
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /platform/status

